import React from 'react';
import { Button, Group, Modal, NativeSelect, SegmentedControl, Switch, Text, Textarea, TextInput } from '@mantine/core';
import { themeVars } from '../../theme/themeVars';
import { confirmDestructive } from '../../utils/confirm';
import { useDialogFocusReturn } from '../../hooks/useDialogFocusReturn';
import { SubmitButton } from '../../components/SubmitButton';
import { api, getErrorMessage } from '../../api/atelier';
import { ejsonParse, ejsonStringify, ejsonStringifyReadable, isPlainDocument } from '../../utils/ejson';
import { refusalMessage, repairOnCommit, repairToCanonicalEjson } from '../../utils/shellSyntax';
import { classifyInsertPayload, type InsertPayloadClassification } from '../../utils/insertPayload';
import { ScriptEditor } from '../../components/ScriptEditor';
import { checkFieldType, inferType, type TypeWarning } from './schemaSummary';
import { getStructureEntries } from '../../features/fieldSuggestions/sources/sampleSchemaSource';
import { FieldAutocompleteInput } from '../../features/fieldSuggestions/FieldAutocompleteInput';
import type { SuggestionContext } from '../../features/fieldSuggestions/types';
import {
  applyDiff,
  buildUpdateRequest,
  deleteAtSegments,
  diff,
  getAtSegments,
  isEdited,
  isEmptyDiff,
  isUnsafeFieldName,
  parseJsonDraft,
  setAtSegments,
  type DocDiff,
} from './documentDiff';
import {
  SELECTABLE_KINDS,
  TYPE_LABEL,
  convertType,
  kindOf,
  parseAs,
  textOf,
  typeLabel,
  type FieldKind,
} from './documentFieldTypes';
import type { SchemaSampleEntry } from '@shared/types';

type Doc = Record<string, unknown>;

interface DocumentEditorBaseProps {
  connectionId: string;
  dbName: string;
  collection: string;
  onClose: () => void;
}

interface EditModeProps extends DocumentEditorBaseProps {
  mode: 'edit';
  /** A result row: canonical EJSON sentinels, as `find` hands them over. */
  doc: unknown;
  /** `auditId` is the Reversible entry id of the update, for undo. */
  onSaved: (auditId?: string) => void;
  /**
   * W18 §8 — Quick Edit opens the editor straight at a field it can't edit
   * inline (Date, ObjectId, Object, Array, …) instead of leaving the user to
   * find the row themselves: scrolled into view and focused once the editor
   * mounts. Always a top-level field name (Quick Edit never targets a
   * computed or nested column), so `data-field`/`aria-label` match it
   * exactly.
   */
  focusPath?: string;
}

interface InsertModeProps extends DocumentEditorBaseProps {
  mode: 'insert';
  /**
   * Pre-fill the draft (W18 §6, "Duplicate document") with the source
   * document's EJSON minus `_id` — the existing `stripIdForDuplicate`
   * helper in `views/docId.ts`. Defaults to the empty document `{}` when
   * omitted (plain "Insert").
   */
  initialDocJson?: string;
  onInserted: () => void;
  /**
   * Called instead of `onInserted`/`onClose` when an ordered `insertMany`
   * fails partway through the batch (a duplicate-key error on doc N of an
   * array leaves docs 0..N-1 persisted). Refresh the grid so the
   * partially-inserted rows are visible, but keep the editor open so the
   * user's unresolved text isn't discarded.
   */
  onPartialInsert?: () => void;
}

type DocumentEditorProps = EditModeProps | InsertModeProps;

const SIZE_PREF_KEY = 'ui.workspace.documentEditorSize';
const DEFAULT_WIDTH = 720;
/** W18 §3 — the filter box appears only past this many top-level fields. */
const FILTER_BOX_THRESHOLD = 15;

interface EditorSize {
  width: number;
  height?: number;
}

function isEditorSize(v: unknown): v is EditorSize {
  if (v === null || typeof v !== 'object') return false;
  const { width, height } = v as Record<string, unknown>;
  return typeof width === 'number' && Number.isFinite(width) && (height === undefined || (typeof height === 'number' && Number.isFinite(height)));
}

/** The row's value, revived: live BSON instances, which `ejsonStringify` writes back with their type. */
function revive(doc: unknown): Doc {
  const revived = ejsonParse<unknown>(JSON.stringify(doc));
  if (!isPlainDocument(revived)) throw new Error('The Document Editor opens a document, not a bare value');
  return revived as Doc;
}

/**
 * The insert/duplicate seed, revived the same way `revive` does for an
 * existing row. Unlike `revive`, malformed or non-document input falls back
 * to the empty draft rather than throwing — this text was generated by
 * `stripIdForDuplicate` (which has the same fallback) or is the plain
 * Insert default, never something the user could have mistyped yet.
 */
function reviveInsertSeed(json: string | undefined): Doc {
  try {
    const parsed = ejsonParse<unknown>(json ?? '{}');
    return isPlainDocument(parsed) ? (parsed as Doc) : {};
  } catch {
    return {};
  }
}

/** One field row's identity, and the map key `texts`/`collapsed` are keyed by. */
const keyOf = (segments: readonly string[]): string => JSON.stringify(segments);

function decodeKey(key: string): string[] | null {
  try {
    const segments = JSON.parse(key) as unknown;
    return Array.isArray(segments) && segments.every((s) => typeof s === 'string') ? (segments as string[]) : null;
  } catch {
    return null;
  }
}

function isUnderSegments(key: string, prefix: readonly string[]): boolean {
  const segments = decodeKey(key);
  if (!segments || segments.length < prefix.length) return false;
  return prefix.every((p, i) => segments[i] === p);
}

/** Drops any entry addressing `segments` or anything nested under it. */
function purgeUnder(m: ReadonlyMap<string, string>, segments: readonly string[]): Map<string, string> {
  const next = new Map(m);
  for (const key of next.keys()) if (isUnderSegments(key, segments)) next.delete(key);
  return next;
}

/**
 * The dotted path to check with `isEdited` (and the W17 warning) for a row at
 * `segments`. A field name with a `.` or a leading `$` can't be its own
 * update path — `diff` (§5a) falls back to resending the nearest ancestor
 * whose own path is safe, so that's what has to be checked here too. A
 * top-level unsafe name has no such ancestor; the row is locked read-only in
 * that case (see `locked` below), so its address is never actually used to
 * decide anything save-relevant.
 */
function editAddress(segments: readonly string[]): string {
  const cut = segments.findIndex((s) => isUnsafeFieldName(s));
  const safe = cut === -1 ? segments : segments.slice(0, cut);
  return (safe.length > 0 ? safe : segments).join('.');
}

interface RowCtx {
  connectionId: string;
  dbName: string;
  collection: string;
  draft: Doc;
  changes: DocDiff;
  texts: ReadonlyMap<string, string>;
  collapsed: ReadonlySet<string>;
  entriesByPath: Map<string, SchemaSampleEntry>;
  /** Root-level-only (W18 §3); narrows visible rows by name, never their edits. */
  filterText: string;
  patchDraft: (updater: (d: Doc) => Doc) => void;
  patchTexts: (updater: (m: ReadonlyMap<string, string>) => ReadonlyMap<string, string>) => void;
  toggleCollapsed: (key: string) => void;
  setErr: (e: string | null) => void;
  /** The "Edit in JSON" link on a read-only ("other" kind) row. */
  switchToJson: () => void;
}

/** Whether some row nested under `segments` holds text that doesn't parse. */
function hasPendingErrorUnder(ctx: RowCtx, segments: readonly string[]): boolean {
  for (const [key, text] of ctx.texts) {
    const rowSegments = decodeKey(key);
    if (!rowSegments || rowSegments.length <= segments.length) continue;
    if (!segments.every((s, i) => rowSegments[i] === s)) continue;
    const found = getAtSegments(ctx.draft, rowSegments);
    if (found && !parseAs(kindOf(found.value), text).ok) return true;
  }
  return false;
}

function warningFor(entriesByPath: Map<string, SchemaSampleEntry>, field: string, value: unknown): TypeWarning | null {
  if (entriesByPath.size === 0 || field.includes('.')) return null;
  // `inferType` reads sentinel shapes, the vocabulary the sample was
  // recorded in, so the revived value goes back to one first.
  const actual = inferType(JSON.parse(ejsonStringify(value)) as unknown);
  return actual === 'object' ? null : checkFieldType(entriesByPath, field, actual);
}

function FieldRow({ ctx, segments, depth }: { ctx: RowCtx; segments: string[]; depth: number }) {
  const T = themeVars;
  const found = getAtSegments(ctx.draft, segments);
  if (!found) return null; // removed by a sibling edit in the same render pass
  const value = found.value;
  const kind = kindOf(value);
  const name = segments[segments.length - 1]!;
  const isRoot = segments.length === 1;
  const locked = isRoot && (name === '_id' || isUnsafeFieldName(name));
  const dotted = segments.join('.');
  const key = keyOf(segments);
  const edited = isEdited(ctx.changes, editAddress(segments));
  const warning = isRoot ? warningFor(ctx.entriesByPath, name, value) : null;

  const hasTypeSelector = !locked && kind !== 'other';
  const hasValueControl = hasTypeSelector && kind !== 'null' && kind !== 'object';
  const removable = !locked;
  // A container stays open, even if the user collapsed it, while a row
  // nested under it holds text that doesn't parse — collapsing must never
  // hide the only explanation for why Save is disabled.
  const isCollapsed = ctx.collapsed.has(key) && !hasPendingErrorUnder(ctx, segments);

  const text = ctx.texts.get(key) ?? (kind === 'array' ? textOf(kind, value) : hasValueControl ? textOf(kind, value) : '');
  const parsedText = hasValueControl && ctx.texts.has(key) ? parseAs(kind, ctx.texts.get(key)!) : null;
  const rowError = parsedText && !parsedText.ok ? parsedText.error : undefined;

  const editText = (nextText: string) => {
    ctx.patchTexts((m) => new Map(m).set(key, nextText));
    ctx.setErr(null);
    const parsed = parseAs(kind, nextText);
    if (parsed.ok) ctx.patchDraft((d) => setAtSegments(d, segments, parsed.value));
  };

  const onTypeChange = (nextKind: FieldKind) => {
    const converted = convertType(kind, nextKind, value);
    ctx.patchDraft((d) => setAtSegments(d, segments, converted));
    ctx.patchTexts((m) => purgeUnder(m, segments));
    ctx.setErr(null);
  };

  const onRemove = () => {
    ctx.patchDraft((d) => deleteAtSegments(d, segments));
    ctx.patchTexts((m) => purgeUnder(m, segments));
    ctx.setErr(null);
  };

  return (
    <div
      role="listitem"
      data-field={dotted}
      data-edited={edited || undefined}
      style={{
        display: 'flex',
        alignItems: 'flex-start',
        gap: 8,
        padding: '4px 6px',
        marginLeft: depth * 16,
        borderLeft: `2px solid ${edited ? T.accent : 'transparent'}`,
      }}
    >
      <div style={{ width: 180, flexShrink: 0, display: 'flex', alignItems: 'center', gap: 4, paddingTop: 4 }}>
        {kind === 'object' && (
          <button
            type="button"
            aria-expanded={!isCollapsed}
            aria-label={`${isCollapsed ? 'Expand' : 'Collapse'} ${dotted}`}
            onClick={() => ctx.toggleCollapsed(key)}
            style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 0, fontSize: 11, lineHeight: 1 }}
          >
            {isCollapsed ? '▸' : '▾'}
          </button>
        )}
        <Text size="sm" ff="monospace" style={{ overflowWrap: 'anywhere' }}>
          {name}
          {edited && (
            <Text span size="xs" c={T.accent} ml={6}>
              edited
            </Text>
          )}
        </Text>
      </div>
      <div style={{ flex: 1, minWidth: 0 }}>
        {!hasValueControl ? (
          kind === 'object' ? null : (
            <div style={{ display: 'flex', alignItems: 'baseline', gap: 8, flexWrap: 'wrap' }}>
              <Text size="sm" ff="monospace" c="dimmed" style={{ overflowWrap: 'anywhere', paddingTop: 4 }}>
                {kind === 'null' ? 'null' : textOf(kind, value)}
              </Text>
              {kind === 'other' && (
                <Button size="compact-xs" variant="subtle" onClick={ctx.switchToJson} px={4}>
                  Edit in JSON
                </Button>
              )}
            </div>
          )
        ) : kind === 'boolean' ? (
          <Switch
            aria-label={dotted}
            checked={value === true}
            onChange={(e) => {
              const { checked } = e.currentTarget;
              ctx.setErr(null);
              ctx.patchDraft((d) => setAtSegments(d, segments, checked));
            }}
            mt={6}
          />
        ) : kind === 'string' || kind === 'array' ? (
          <Textarea
            aria-label={dotted}
            value={text}
            onChange={(e) => editText(e.currentTarget.value)}
            error={rowError}
            // Grows past one line natively (Chromium's `field-sizing`),
            // without Mantine's JS autosize.
            rows={1}
            styles={{ input: { fieldSizing: 'content', maxHeight: 160 } }}
            size="xs"
            ff="monospace"
            spellCheck={false}
          />
        ) : (
          <TextInput
            aria-label={dotted}
            value={text}
            onChange={(e) => editText(e.currentTarget.value)}
            error={rowError}
            inputMode={kind === 'date' || kind === 'objectId' ? undefined : 'decimal'}
            size="xs"
            ff="monospace"
            spellCheck={false}
            description={kind === 'date' && value instanceof Date ? `Local: ${value.toLocaleString()}` : undefined}
            inputWrapperOrder={['label', 'input', 'description', 'error']}
          />
        )}
        {warning && (
          <Text size="xs" c="dimmed" mt={2} data-testid="document-editor-type-warning">
            {`Field "${warning.field}" is usually ${warning.expectedType} (${warning.percent}% of sampled documents). This value is ${warning.actualType}.`}
          </Text>
        )}
      </div>
      <div style={{ width: 110, flexShrink: 0, paddingTop: 2 }}>
        {hasTypeSelector ? (
          <NativeSelect
            aria-label={`${dotted} type`}
            value={kind}
            // A bare JS number isn't a selectable target — bson infers its
            // saved type, not this selector — so it gets a disabled
            // placeholder option instead of being folded into 'double',
            // which would make Double look already selected and take a
            // click to convert without firing onChange.
            data={[
              ...(kind === 'number' ? [{ value: 'number', label: TYPE_LABEL.number, disabled: true }] : []),
              ...SELECTABLE_KINDS.map((k) => ({ value: k, label: TYPE_LABEL[k] })),
            ]}
            onChange={(e) => onTypeChange(e.currentTarget.value as FieldKind)}
            size="xs"
          />
        ) : (
          <Text size="xs" c="dimmed" style={{ paddingTop: 6 }}>
            {typeLabel(kind, value)}
          </Text>
        )}
      </div>
      <div style={{ width: 28, flexShrink: 0 }}>
        {removable && (
          <Button
            size="compact-xs"
            variant="subtle"
            color="red"
            aria-label={`Remove ${dotted}`}
            onClick={onRemove}
            px={4}
          >
            &times;
          </Button>
        )}
      </div>
      {kind === 'object' && !isCollapsed && (
        <div style={{ width: '100%' }}>
          <RowsList ctx={ctx} parentSegments={segments} depth={depth + 1} />
        </div>
      )}
    </div>
  );
}

function AddFieldRow({
  ctx,
  parentSegments,
  existing,
  depth,
}: {
  ctx: RowCtx;
  parentSegments: readonly string[];
  existing: readonly string[];
  depth: number;
}) {
  const [name, setName] = React.useState('');
  const [err, setErrLocal] = React.useState<string | null>(null);
  const isRootLevel = parentSegments.length === 0;

  const suggestionContext: SuggestionContext = React.useMemo(
    () => ({ connectionId: ctx.connectionId, dbName: ctx.dbName, collection: ctx.collection }),
    [ctx.connectionId, ctx.dbName, ctx.collection],
  );
  const ariaLabel = isRootLevel ? 'New field name' : `New field name under ${parentSegments.join('.')}`;

  const submit = () => {
    const trimmed = name.trim();
    if (trimmed === '') return;
    if (existing.includes(trimmed)) {
      setErrLocal(`A field named "${trimmed}" already exists`);
      return;
    }
    if (isRootLevel && isUnsafeFieldName(trimmed)) {
      setErrLocal('This name cannot be saved from here: it must not contain "." or start with "$"');
      return;
    }
    ctx.patchDraft((d) => setAtSegments(d, [...parentSegments, trimmed], ''));
    ctx.setErr(null);
    setName('');
    setErrLocal(null);
  };

  return (
    <div
      data-testid={`add-field-${isRootLevel ? 'root' : parentSegments.join('.')}`}
      style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '4px 6px', marginLeft: (depth + 1) * 16 }}
    >
      <div style={{ flex: 1, minWidth: 0, maxWidth: 260 }}>
        <FieldAutocompleteInput
          value={name}
          onChange={(v) => {
            setName(v);
            setErrLocal(null);
          }}
          context={suggestionContext}
          ariaLabel={ariaLabel}
          placeholder="Add field"
          onKeyDown={(e) => {
            if (e.key === 'Enter') {
              e.preventDefault();
              submit();
            }
          }}
          style={{ width: '100%', fontFamily: 'monospace', fontSize: 12, padding: '4px 6px' }}
        />
      </div>
      <Button size="compact-xs" variant="default" disabled={name.trim() === ''} onClick={submit}>
        Add field
      </Button>
      {err && (
        <Text size="xs" c="red">
          {err}
        </Text>
      )}
    </div>
  );
}

function RowsList({ ctx, parentSegments, depth }: { ctx: RowCtx; parentSegments: readonly string[]; depth: number }) {
  const isRoot = parentSegments.length === 0;
  const found = isRoot ? { value: ctx.draft as unknown } : getAtSegments(ctx.draft, parentSegments);
  const obj = found && isPlainDocument(found.value) ? (found.value as Doc) : {};
  const allKeys = Object.keys(obj);
  // The filter box is root-only (W18 §3): a nested object's own rows are
  // never narrowed, only which top-level rows are shown.
  const needle = isRoot ? ctx.filterText.trim().toLowerCase() : '';
  const keys = needle ? allKeys.filter((k) => k.toLowerCase().includes(needle)) : allKeys;
  return (
    <div
      role="list"
      aria-label={isRoot ? 'Fields' : `Fields of ${parentSegments.join('.')}`}
      style={{ minHeight: 0 }}
    >
      {keys.map((k) => (
        <FieldRow key={k} ctx={ctx} segments={[...parentSegments, k]} depth={depth} />
      ))}
      <AddFieldRow ctx={ctx} parentSegments={parentSegments} existing={allKeys} depth={depth} />
    </div>
  );
}

/** `{ doc }` from a committed Fields-shaped draft, or `{ docs }` from a
 * top-level array — only reachable in `mode: 'insert'` (§6). */
type JsonCommit = { kind: 'doc'; doc: Doc } | { kind: 'array'; docs: unknown[] };

export function DocumentEditor(props: DocumentEditorProps) {
  const { connectionId, dbName, collection, onClose, mode } = props;
  const onSaved = props.mode === 'edit' ? props.onSaved : undefined;
  const focusPath = props.mode === 'edit' ? props.focusPath : undefined;
  const onInserted = props.mode === 'insert' ? props.onInserted : undefined;
  const onPartialInsert = props.mode === 'insert' ? props.onPartialInsert : undefined;

  const seedDoc = () => (props.mode === 'edit' ? revive(props.doc) : reviveInsertSeed(props.initialDocJson));

  const [original, setOriginal] = React.useState<Doc>(seedDoc);
  const [draft, setDraft] = React.useState<Doc>(seedDoc);
  // Text as typed, only for rows the user has touched, keyed by
  // `keyOf(segments)`. A value that doesn't parse stays here, and out of the
  // draft, until it does.
  const [texts, setTexts] = React.useState<ReadonlyMap<string, string>>(() => new Map());
  const [collapsed, setCollapsed] = React.useState<ReadonlySet<string>>(() => new Set());
  const [err, setErr] = React.useState<string | null>(null);
  const [conflict, setConflict] = React.useState<'changed' | 'deleted' | null>(null);
  const [busy, setBusy] = React.useState(false);
  const [filterText, setFilterText] = React.useState('');

  // W18 §2/§4 — the JSON view's own draft of the same document, as Shell
  // Syntax text (X14). It is regenerated from `draft` on every switch *into*
  // this view, and only written back into `draft` on a successful switch
  // away or Save — never per keystroke, so a half-typed edit is never
  // reflected (or lost) behind the user's back.
  const [view, setView] = React.useState<'fields' | 'json'>('fields');
  const [jsonText, setJsonText] = React.useState('');

  // One diff drives the edited markers, the dirty guard and the save, so the
  // three cannot disagree. In `mode: 'insert'` `original` is the seed the
  // editor opened with (the empty document, or the duplicate source minus
  // `_id`) — there is no server copy to diff against (§6) — so this is
  // "differs from what the draft started as", the same thing it means in
  // `mode: 'edit'`.
  const changes = React.useMemo(() => diff(original, draft), [original, draft]);
  const rowErrors = React.useMemo(() => {
    const out = new Map<string, string>();
    for (const [key, text] of texts) {
      const segments = decodeKey(key);
      if (!segments) continue;
      const found = getAtSegments(draft, segments);
      if (!found) continue; // the row was removed or its type changed since
      const parsed = parseAs(kindOf(found.value), text);
      if (!parsed.ok) out.set(key, parsed.error);
    }
    return out;
  }, [texts, draft]);

  // Live, from the raw `jsonText` — never written back until a commit point
  // (blur, switch, Save), the same asymmetry X14's read surfaces use. The
  // transform's own refusal comes first; a text that repairs but isn't
  // usable fails a second, mode-specific check instead.
  const jsonOutcome = React.useMemo(() => repairToCanonicalEjson(jsonText), [jsonText]);
  const jsonLiveError = React.useMemo(() => {
    if (jsonOutcome.kind === 'failed') return refusalMessage(jsonText, jsonOutcome);
    const canonical = jsonOutcome.kind === 'repaired' ? jsonOutcome.text : jsonText;
    if (mode === 'edit') {
      const parsed = parseJsonDraft(canonical, original._id);
      return parsed.ok ? null : parsed.error;
    }
    // mode: 'insert' — a document or a top-level array of documents, per §6.
    let parsedValue: unknown;
    try {
      parsedValue = ejsonParse(canonical);
    } catch {
      return 'Invalid EJSON';
    }
    const cls = classifyInsertPayload(parsedValue);
    if (cls.kind === 'array-empty') return 'Array must contain at least one document';
    if (cls.kind === 'array-invalid-items') return 'Every array item must be a document';
    if (cls.kind === 'single' && !isPlainDocument(parsedValue)) return 'Enter a JSON document or an array of documents';
    return null;
  }, [jsonOutcome, jsonText, original, mode]);

  // Repairs and commits `jsonText` (writing the canonical text back into the
  // box, per X14), then parses it into a draft document or (`mode: 'insert'`
  // only) an array to insert-many. Null means refused — `jsonLiveError`
  // already carries why, recomputed from the (possibly now repaired) text on
  // the next render.
  const commitJson = (): JsonCommit | null => {
    const result = repairOnCommit(jsonText, setJsonText);
    if (result.outcome.kind === 'failed') return null;
    if (mode === 'edit') {
      const parsed = parseJsonDraft(result.text, original._id);
      return parsed.ok ? { kind: 'doc', doc: parsed.doc } : null;
    }
    let parsedValue: unknown;
    try {
      parsedValue = ejsonParse(result.text);
    } catch {
      return null;
    }
    const cls = classifyInsertPayload(parsedValue);
    if (cls.kind === 'array-empty' || cls.kind === 'array-invalid-items') return null;
    if (cls.kind === 'array') return { kind: 'array', docs: parsedValue as unknown[] };
    if (!isPlainDocument(parsedValue)) return null;
    return { kind: 'doc', doc: parsedValue as Doc };
  };

  const switchToJson = () => {
    // A row's typed text that doesn't parse lives only in `texts`, out of
    // `draft` — building `jsonText` from `draft` alone would show the old
    // value, and the switch away from Fields (§4a) clears `texts`
    // unconditionally, so that text would vanish with no warning.
    if (rowErrors.size > 0) {
      setErr('Fix the invalid values in Fields before switching to JSON');
      return;
    }
    setJsonText(ejsonStringifyReadable(draft, 2));
    setView('json');
  };

  const trySwitchToFields = () => {
    const result = commitJson();
    if (!result) return; // refused; stays on JSON with the text and error intact
    if (result.kind === 'array') {
      // W18 §6 — Fields shows one document; an array stays on JSON.
      setErr('Fields view is not available for an array of documents. Edit it here, or Insert to add them all.');
      return;
    }
    setDraft(result.doc);
    setTexts(new Map());
    setView('fields');
  };

  const isDirty =
    !isEmptyDiff(changes) ||
    rowErrors.size > 0 ||
    (view === 'json' && jsonText !== ejsonStringifyReadable(draft, 2));

  const close = useDialogFocusReturn(onClose);

  const requestClose = async () => {
    if (!isDirty) return close();
    const discard = await confirmDestructive({
      title: 'Discard changes?',
      body: 'This closes the editor and loses what you typed.',
      confirmLabel: 'Discard',
    });
    if (discard) close();
  };

  // W17 — read-only: nothing here feeds the save, and nothing disables it.
  const [structureEntries, setStructureEntries] = React.useState<SchemaSampleEntry[]>([]);
  React.useEffect(() => {
    let live = true;
    void getStructureEntries(connectionId, dbName, collection).then((entries) => {
      if (live) setStructureEntries(entries);
    });
    return () => {
      live = false;
    };
  }, [connectionId, dbName, collection]);
  const entriesByPath = React.useMemo(() => new Map(structureEntries.map((e) => [e.path, e])), [structureEntries]);

  const sendEdit = async (guarded: boolean) => {
    // Same guard as the Save button's `disabled`: ⌘↵ calls sendEdit()
    // directly, bypassing the button, so a deleted document must be checked
    // here too.
    if (busy || conflict === 'deleted') return;
    let nextDraft = draft;
    if (view === 'json') {
      const result = commitJson();
      if (!result || result.kind !== 'doc') return; // refused; jsonLiveError already shows why
      nextDraft = result.doc;
      setDraft(result.doc);
    } else if (rowErrors.size > 0) {
      return;
    }
    let request;
    try {
      request = buildUpdateRequest(original, nextDraft);
    } catch (e) {
      setErr(getErrorMessage(e, 'Cannot save this document'));
      return;
    }
    if (request === null) {
      close();
      return;
    }
    setBusy(true);
    setErr(null);
    try {
      const res = await api.doc.updateOne({
        connectionId,
        dbName,
        collection,
        filterJson: guarded ? request.filterJson : request.idFilterJson,
        updateJson: request.updateJson,
      });
      // Unguarded, the filter is `_id` alone: nothing matching means the
      // document is gone, not that someone changed it.
      if (res.matchedCount === 0) setConflict(guarded ? 'changed' : 'deleted');
      else {
        onSaved?.(res.auditId);
        // Through the focus-returning wrapper, so a save hands focus back
        // to whatever opened the editor, like Cancel does.
        close();
      }
    } catch (e) {
      setErr(getErrorMessage(e, 'Save failed'));
    } finally {
      setBusy(false);
    }
  };

  // W18 §6 — Insert sends the whole draft; there is no diff for a document
  // that doesn't exist yet. A top-level array routes to `doc:insertMany`
  // instead, via `classifyInsertPayload`.
  const sendInsert = async () => {
    if (busy) return;
    let payload: Doc | unknown[] = draft;
    if (view === 'json') {
      const result = commitJson();
      if (!result) return; // refused; jsonLiveError already shows why
      if (result.kind === 'array') {
        payload = result.docs;
      } else {
        setDraft(result.doc);
        payload = result.doc;
      }
    } else if (rowErrors.size > 0) {
      return;
    }
    // Only 'array' or 'single' can reach here: `commitJson` above already
    // refuses 'array-empty'/'array-invalid-items', and the Fields view can
    // only ever hold a plain document.
    const cls = classifyInsertPayload(payload);
    setBusy(true);
    setErr(null);
    try {
      if (cls.kind === 'array') {
        await api.doc.insertMany({ connectionId, dbName, collection, docsJson: ejsonStringify(payload) });
      } else {
        await api.doc.insert({ connectionId, dbName, collection, docJson: ejsonStringify(payload) });
      }
      onInserted?.();
      close();
    } catch (e) {
      const code = (e as { code?: string }).code;
      const details = (e as { details?: unknown }).details;
      const msg = getErrorMessage(e, 'Insert failed');
      const base = code === 'CONFLICT' ? `Conflict: ${msg}` : msg;
      const insertedCount =
        cls.kind === 'array' && details !== null && typeof details === 'object'
          ? (details as { insertedCount?: unknown }).insertedCount
          : undefined;
      if (cls.kind === 'array' && typeof insertedCount === 'number' && insertedCount > 0) {
        setErr(`${base} (${insertedCount} of ${cls.count} documents inserted before the error)`);
        onPartialInsert?.();
      } else {
        setErr(base);
      }
    } finally {
      setBusy(false);
    }
  };

  const handleSave = () => (mode === 'edit' ? sendEdit(true) : sendInsert());

  const reload = async () => {
    if (busy) return;
    setBusy(true);
    setErr(null);
    try {
      // `changes` (the outer diff) reflects only `draft` — in the JSON view,
      // text typed since the last commit point lives in `jsonText` alone.
      // Committing it first, and diffing from that, is what keeps a JSON
      // edit made after a failed Save from being silently dropped here.
      let baseChanges = changes;
      if (view === 'json') {
        const committed = commitJson();
        if (!committed || committed.kind !== 'doc') return; // refused; jsonLiveError already shows why, text kept
        setDraft(committed.doc);
        baseChanges = diff(original, committed.doc);
      }
      const res = await api.query.findOne({
        connectionId,
        dbName,
        collection,
        filter: ejsonStringify({ _id: original._id }),
      });
      if (res.document === null) {
        setConflict('deleted');
        return;
      }
      const fresh = revive(res.document);
      // The user's edits win over the server's on a path both changed; that
      // path stays in the diff, so the next Save guards it again.
      const merged = applyDiff(fresh, baseChanges);
      setOriginal(fresh);
      setDraft(merged);
      // The JSON view's own buffer is a separate draft (W18 §4) — refresh it
      // too, or Reload's merge would be invisible behind stale text.
      if (view === 'json') setJsonText(ejsonStringifyReadable(merged, 2));
      setTexts((m) => {
        const next = new Map<string, string>();
        for (const [key, text] of m) {
          const segments = decodeKey(key);
          if (segments && isEdited(baseChanges, editAddress(segments))) next.set(key, text);
        }
        return next;
      });
      setConflict(null);
    } catch (e) {
      setErr(getErrorMessage(e, 'Reload failed'));
    } finally {
      setBusy(false);
    }
  };

  // ⌘↵ only: ⌘S is deliberately not a save key. PanelBody's own ⌘↵ (Run)
  // already skips events from inside a dialog.
  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key !== 'Enter' || !(e.metaKey || e.ctrlKey) || e.shiftKey || e.altKey) return;
    e.preventDefault();
    void handleSave();
  };

  const [size, setSize] = React.useState<EditorSize>({ width: DEFAULT_WIDTH });
  const renderedSize = React.useRef(size);
  // Layout effect: it lands before the browser's resize notifications for the
  // same frame, so a size just rendered is never mistaken for a drag.
  React.useLayoutEffect(() => {
    renderedSize.current = size;
  }, [size]);
  React.useEffect(() => {
    let live = true;
    void api.prefs
      .get<unknown>(SIZE_PREF_KEY)
      .then((v) => {
        if (live && isEditorSize(v)) setSize(v);
      })
      // An unreadable pref leaves the default size, which is all it can mean.
      .catch(() => undefined);
    return () => {
      live = false;
    };
  }, []);
  // The browser writes an inline width/height only when the user drags the
  // resize handle, so an inline size that differs from the rendered one is a
  // resize to remember — content growing inside an auto height is not.
  const observer = React.useRef<ResizeObserver | null>(null);
  const containerRef = React.useRef<HTMLDivElement | null>(null);
  const surfaceRef = React.useCallback((el: HTMLDivElement | null) => {
    containerRef.current = el;
    observer.current?.disconnect();
    observer.current = null;
    if (!el) return;
    let timer: ReturnType<typeof setTimeout> | undefined;
    observer.current = new ResizeObserver(() => {
      const width = Number.parseFloat(el.style.width);
      const height = Number.parseFloat(el.style.height);
      if (!Number.isFinite(width) || !Number.isFinite(height)) return;
      const shown = renderedSize.current;
      if (width === shown.width && height === shown.height) return;
      clearTimeout(timer);
      timer = setTimeout(() => {
        // Losing a remembered size costs nothing but the next open's width.
        void api.prefs.set(SIZE_PREF_KEY, { width, height }).catch(() => undefined);
      }, 300);
    });
    observer.current.observe(el);
  }, []);

  // W18 §8 — Quick Edit's "open the editor on that field": scroll the row
  // into view, and marks its control `data-autofocus` for Mantine's own
  // `FocusTrap` (`@mantine/hooks`' `useFocusTrap`) to focus. `focusPath` is
  // fixed for this instance's whole lifetime (it comes from the props that
  // created it), and Fields — where the row lives — is always the view on
  // open (§2's default), so this never has to react to a later change.
  //
  // Marking the attribute rather than calling `.focus()` directly is
  // load-bearing, not stylistic: the trap schedules its own initial-focus
  // pass with `setTimeout(0)` (`use-focus-trap.ts`'s `setRef`/mount effect,
  // both deferred), which always runs after this effect's synchronous body
  // — a direct `.focus()` here would just lose that race and read as
  // "focused" for one tick before the trap grabs it back to the modal's
  // Close button. `querySelector('[data-autofocus]')` is the trap's own
  // first lookup, ahead of its tabbable-element fallback, so setting the
  // attribute now is visible to it whenever it actually runs.
  React.useEffect(() => {
    if (!focusPath) return;
    const path = focusPath;
    const container = containerRef.current;
    if (!container) return;
    const escaped = CSS.escape(path);
    const rowEl = container.querySelector(`[data-field="${escaped}"]`);
    rowEl?.scrollIntoView({ block: 'center' });
    // The row's own value control (Switch/TextInput/Textarea share the
    // `aria-label={dotted}` convention); an Object row has none of those and
    // gets its collapse toggle instead, and an 'other' row its "Edit in
    // JSON" link — both live inside `rowEl`.
    const control =
      container.querySelector(`[aria-label="${escaped}"]`) ??
      rowEl?.querySelector('button') ??
      null;
    control?.setAttribute('data-autofocus', 'true');
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // W18 §6 — the Insert button label, live off the uncommitted JSON buffer:
  // an array shows its count before Save is even pressed, and stays current
  // as the user keeps editing (never off a value captured at an earlier
  // commit).
  const livePayload = React.useMemo<InsertPayloadClassification | null>(() => {
    if (mode !== 'insert') return null;
    if (view === 'fields') return { kind: 'single' };
    if (jsonOutcome.kind === 'failed') return null;
    const canonical = jsonOutcome.kind === 'repaired' ? jsonOutcome.text : jsonText;
    try {
      return classifyInsertPayload(ejsonParse(canonical));
    } catch {
      return null;
    }
  }, [mode, view, jsonOutcome, jsonText]);

  const submitLabel =
    mode === 'edit'
      ? busy
        ? 'Saving…'
        : 'Save'
      : livePayload?.kind === 'array'
        ? busy
          ? `Inserting ${livePayload.count} documents…`
          : `Insert ${livePayload.count} documents`
        : busy
          ? 'Inserting…'
          : 'Insert';

  const ctx: RowCtx = {
    connectionId,
    dbName,
    collection,
    draft,
    changes,
    texts,
    collapsed,
    entriesByPath,
    filterText,
    patchDraft: (updater) => setDraft(updater),
    patchTexts: (updater) => setTexts(updater),
    toggleCollapsed: (key) =>
      setCollapsed((s) => {
        const next = new Set(s);
        if (next.has(key)) next.delete(key);
        else next.add(key);
        return next;
      }),
    setErr,
    switchToJson,
  };

  return (
    // `closeOnClickOutside={false}` is load-bearing: one stray click on the
    // backdrop must not reach the close path and discard a typed draft.
    // Escape still closes, through `requestClose` and its prompt.
    <Modal
      opened
      onClose={() => void requestClose()}
      title={mode === 'edit' ? 'Edit document' : 'Insert document'}
      centered
      size="auto"
      closeOnClickOutside={false}
      // The 80vh cap sits on the whole dialog, header included, and the body
      // is a flex column so the surface shrinks under it instead of pushing
      // Save past the viewport; the field list is what scrolls.
      styles={{
        content: { display: 'flex', flexDirection: 'column', maxHeight: '80vh', overflow: 'hidden' },
        body: { flex: 1, minHeight: 0, display: 'flex', flexDirection: 'column' },
      }}
    >
      <div
        ref={surfaceRef}
        data-testid="document-editor-surface"
        onKeyDown={handleKeyDown}
        style={{
          width: size.width,
          height: size.height,
          minWidth: 360,
          minHeight: 0,
          maxWidth: '95vw',
          resize: 'both',
          overflow: 'hidden',
          display: 'flex',
          flexDirection: 'column',
          gap: 8,
        }}
      >
        <Group justify="space-between" align="center">
          <Text size="xs" c="dimmed" ff="monospace">{`${dbName}.${collection}`}</Text>
          <SegmentedControl
            size="xs"
            aria-label="View"
            value={view}
            onChange={(next) => (next === 'json' ? switchToJson() : trySwitchToFields())}
            data={[
              { label: 'Fields', value: 'fields' },
              { label: 'JSON', value: 'json' },
            ]}
          />
        </Group>

        {view === 'json' ? (
          <div style={{ flex: 1, minHeight: 0, display: 'flex', flexDirection: 'column', gap: 4 }}>
            <div style={{ flex: 1, minHeight: 0 }}>
              <ScriptEditor
                value={jsonText}
                onChange={(next) => {
                  setJsonText(next);
                  setErr(null);
                }}
                onBlur={() => void commitJson()}
                height="100%"
                ariaLabel="Document JSON"
                testId="document-editor-json"
              />
            </div>
            {jsonLiveError && (
              <Text size="xs" c="red" role="alert">
                {jsonLiveError}
              </Text>
            )}
          </div>
        ) : (
          <div style={{ flex: 1, minHeight: 0, overflow: 'auto' }}>
            {Object.keys(draft).length > FILTER_BOX_THRESHOLD && (
              <TextInput
                aria-label="Filter fields"
                placeholder="Filter fields"
                value={filterText}
                onChange={(e) => setFilterText(e.currentTarget.value)}
                size="xs"
                mb={4}
              />
            )}
            <RowsList ctx={ctx} parentSegments={[]} depth={0} />
          </div>
        )}

        {conflict === 'changed' && (
          <div role="alert" style={{ fontSize: 12, padding: '6px 8px', borderRadius: themeVars.rs, background: themeVars.warnSoft, color: themeVars.warnText }}>
            This document changed since you opened it. Reload puts your edits on top of the current version;
            Overwrite saves them over it.
            <Group gap={6} mt={6}>
              <Button size="compact-xs" variant="default" onClick={() => void reload()}>
                Reload
              </Button>
              <Button size="compact-xs" variant="default" color="red" onClick={() => void sendEdit(false)}>
                Overwrite
              </Button>
            </Group>
          </div>
        )}
        {conflict === 'deleted' && (
          <div role="alert" style={{ fontSize: 12, padding: '6px 8px', borderRadius: themeVars.rs, background: themeVars.redSoft, color: themeVars.redText }}>
            This document was deleted since you opened it. There is nothing left to save to.
          </div>
        )}
        {err && (
          <div role="alert" style={{ fontSize: 12, padding: '6px 8px', borderRadius: themeVars.rs, background: themeVars.redSoft, color: themeVars.redText }}>
            {err}
          </div>
        )}

        <Group justify="flex-end" gap={8}>
          <Button size="compact-sm" variant="default" onClick={() => void requestClose()}>
            Cancel
          </Button>
          <SubmitButton
            size="compact-sm"
            submitting={busy}
            disabled={(view === 'fields' ? rowErrors.size > 0 : jsonLiveError !== null) || conflict === 'deleted'}
            onClick={() => void handleSave()}
          >
            {submitLabel}
          </SubmitButton>
        </Group>
      </div>
    </Modal>
  );
}
