#!/usr/bin/env node
// Regenerates src/fonts.css and the woff2 files under src/assets/fonts/.
//
// The fonts are committed, so this is not part of any build — run it only to
// pick up a new upstream version. Committing the binaries is deliberate: it
// keeps `npm install` offline-clean and means a clone always renders correctly.
//
// Latin + latin-ext only. Other subsets (Cyrillic, Greek, Vietnamese) are
// dropped to keep the bundle small; those scripts fall back to the system
// stack, which is what happened before self-hosting anyway.
import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const OUT_DIR = 'src/assets/fonts';
const KEEP = new Set(['latin', 'latin-ext']);

// A modern browser UA is required — Google serves woff2 only to clients it
// believes support it, and falls back to ttf otherwise.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0 Safari/537.36';

// `wght@300..900` requests the variable font: one file spans every weight.
const API =
  'https://fonts.googleapis.com/css2?family=Inter:wght@300..900' +
  '&family=JetBrains+Mono:wght@400..700&display=swap';

const res = await fetch(API, { headers: { 'User-Agent': UA } });
if (!res.ok) throw new Error(`Google Fonts CSS request failed: ${res.status}`);
const css = await res.text();

const blocks = [...css.matchAll(/\/\* ([\w-]+) \*\/\s*(@font-face \{[^}]*\})/g)];
if (blocks.length === 0) throw new Error('No @font-face blocks parsed — the API response shape changed');

// Download and validate everything into memory BEFORE touching the working
// tree. Writing as we go would leave a half-replaced font set behind if a
// later request 404s or the response shape changes — and the failure would be
// silent, because a mixed set still builds and still renders.
const staged = [];
for (const [, subset, block] of blocks) {
  if (!KEEP.has(subset)) continue;
  const family = /font-family: '([^']+)'/.exec(block)[1];
  const url = /url\((https:\/\/[^)]+)\)/.exec(block)[1];
  const name = `${family.toLowerCase().replaceAll(' ', '-')}-${subset}.woff2`;

  const font = await fetch(url);
  if (!font.ok) throw new Error(`Font download failed for ${name}: ${font.status}`);
  const bytes = Buffer.from(await font.arrayBuffer());

  // wOF2 magic number. Guards against a captive portal or an error page being
  // written out as a font, which would otherwise fail much later and obscurely.
  if (bytes.subarray(0, 4).toString('latin1') !== 'wOF2') {
    throw new Error(`${name} is not a woff2 file — got ${bytes.length} bytes starting ${bytes.subarray(0, 4).toString('hex')}`);
  }

  staged.push({ name, bytes, block: block.replace(url, `./assets/fonts/${name}`) });
}

if (staged.length !== 4) throw new Error(`Expected 4 subsets, resolved ${staged.length} — nothing written`);

// Past this point every download succeeded and every file is a real woff2, so
// the replacement is safe to commit to disk.
mkdirSync(OUT_DIR, { recursive: true });
for (const { name, bytes } of staged) {
  writeFileSync(join(OUT_DIR, name), bytes);
  process.stdout.write(`${name}  ${(bytes.length / 1024).toFixed(1)} KB\n`);
}

const kept = staged.map((f) => f.block);

writeFileSync(
  'src/fonts.css',
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.

   Self-hosted so the app makes no third-party request at runtime, and so a
   strict CSP needs no font-src/style-src exception. These are variable fonts:
   one file per subset covers every weight the UI uses (Inter 300-900,
   JetBrains Mono 400-700 — the mono range covers 600 and 700 because the
   aggregation panes ask for them, and a range that stopped at 500 would leave
   the browser to synthesise a fake bold), which is why there are two families and four files
   rather than eight single-weight ones.

   Both families are SIL OFL 1.1. The licence texts live in public/fonts/ so
   Vite copies them into the build output verbatim — the OFL requires the
   notice to travel with every redistributed copy, and Vite only emits assets
   that something references, so keeping them next to the woff2 files in src/
   left them out of the packaged app. */

${kept.join('\n\n')}
`,
);
